### PR TITLE
Create CoZ Application Form.md

### PR DESCRIPTION
**Pull request by anfn101**
Application v1

### CODE REVIEW

**Comment by anfn101** [comment]
Please merge, this is just documentation and link to the CoZ application.

**Comment by canesin** [comment]
Why we are restricting collaboration ? Aren't we open to receive any contribution in our repos from whoever does it ?

**Comment by anfn101** [comment]
Anyone can contribute to CoZ, yes, but this is just so that we can weed people out who keep asking to join dev... Do you have any suggestions for rewording? I did have this up in the Slack for a day or so asking for suggestions...

**Comment by Ejhfast** [comment]
i agree with @canesin, would prefer to keep open to normal pull request model, can add people to CoZ as seems appropriate. maybe i misunderstand the point of the doc though

**Comment by Ejhfast** [comment]
we have the non-filtered dev channel as well as the filtered one right?

**Comment by anfn101** [comment]
Yes, this is for people who want to join the closed dev talk, etc. I think we talked about creating this form a few weeks ago so people didn't keep pinging us for dev access. Also, this helps us keep track of people who can do X in case we need help in an area.

**Comment by anfn101** [comment]
Any suggestions are very welcome though, I can change any wording as needed

**Comment by canesin** [comment]
@anfn101 the wording is important .. sorry but I didn't see the form before if this was discussed.

> "In order to apply to work with us, in the form, please .."
Should really be something like:
> "if you want to help in one of our projects you can do it directly through GitHub, our organization url is https://github.com/CityOfZion. You can also join us on project specific  Slack channels, for such please use the form bellow ..."

**Comment by anfn101** [comment]
got it, changing it now

**Comment by canesin** [comment]
@anfn101 don't need to close the PR, you can just push the update to the same branch you requested the merge, the PR will automatically include new changes..

**Comment by anfn101** [comment]
ok, updated... please take a look

**Comment by Ejhfast** [comment]
i like the intro better, could we get rid of "cover letter" and "successful applicants" stuff though?

**Comment by anfn101** [comment]
changed again

**Pull request merged**
